# GNU Makefile for compiling Win64 quakespasm.exe using MinGW-w64.
# Usage: "make -f Makefile.w64"
# To cross-compile on Linux hosts, see the build_cross_win32*.sh scripts.
# "make DEBUG=1" to build a debug client.
# "make SDL_CONFIG=/path/to/sdl-config" to override the locally included SDL versions.

### Enable/disable SDL2
USE_SDL2=1

### Enable/disable codecs for streaming music support
USE_CODEC_WAVE=1
USE_CODEC_FLAC=1
USE_CODEC_MP3=1
USE_CODEC_VORBIS=1
USE_CODEC_OPUS=1
# either xmp or mikmod (or modplug)
USE_CODEC_MIKMOD=0
USE_CODEC_XMP=1
USE_CODEC_MODPLUG=0
USE_CODEC_UMX=1

# which library to use for mp3 decoding: mad or mpg123
MP3LIB=mad
# which library to use for ogg decoding: vorbis or tremor
VORBISLIB=vorbis

# ---------------------------
# Helper functions
# ---------------------------

check_gcc = $(shell if echo | $(CC) $(1) -Werror -S -o /dev/null -xc - > /dev/null 2>&1; then echo "$(1)"; else echo "$(2)"; fi;)

# ---------------------------

DEBUG   ?= 0
USE_ZLIB?= 1
USE_GNUTLS?= 1

# ---------------------------
# build variables
# ---------------------------

CC = gcc
LINKER = $(CC)
WINDRES = windres

CC_MACHINE := $(shell $(CC) -dumpmachine 2>/dev/null)
ifeq ($(findstring mingw,$(CC_MACHINE)),mingw)
ifneq ($(shell command -v $(CC_MACHINE)-pkg-config 2>/dev/null),)
PKG_CONFIG ?= $(CC_MACHINE)-pkg-config
else ifneq ($(shell command -v $(CC_MACHINE)-pkgconf 2>/dev/null),)
PKG_CONFIG ?= $(CC_MACHINE)-pkgconf
else
PKG_CONFIG ?= pkg-config
endif
else
PKG_CONFIG ?= pkg-config
endif

define gnutls_pkg_probe
$(shell if command -v $(1) >/dev/null 2>&1 && $(1) --exists gnutls 2>/dev/null; then \
	cflags="$$( $(1) --cflags gnutls 2>/dev/null )"; \
	printf '%s\n' '#include <gnutls/gnutls.h>' 'int main(void){return 0;}' | $(CC) -DGNUTLS_STATIC -DGNUTLS_INTERNAL_BUILD $$cflags -Werror -S -o /dev/null -xc - >/dev/null 2>&1 && echo yes; \
fi)
endef

GNUTLS_PKG_OK := $(call gnutls_pkg_probe,$(PKG_CONFIG))
ifeq ($(GNUTLS_PKG_OK),)
ifneq ($(PKG_CONFIG),pkg-config)
ifeq ($(call gnutls_pkg_probe,pkg-config),yes)
PKG_CONFIG := pkg-config
GNUTLS_PKG_OK := yes
endif
endif
endif
GNUTLS_PKG_CFLAGS := $(if $(GNUTLS_PKG_OK),$(shell $(PKG_CONFIG) --cflags gnutls 2>/dev/null))
GNUTLS_PKG_LIBS := $(if $(GNUTLS_PKG_OK),$(shell $(PKG_CONFIG) --libs gnutls 2>/dev/null))
GNUTLS_HOST_CFLAGS_RAW := $(shell command -v pkg-config >/dev/null 2>&1 && pkg-config --exists gnutls 2>/dev/null && pkg-config --cflags gnutls 2>/dev/null)
GNUTLS_HOST_CFLAGS := $(filter-out -I/usr/include -isystem /usr/include,$(GNUTLS_HOST_CFLAGS_RAW))
GNUTLS_HOST_INC_FALLBACK := $(if $(wildcard /usr/include/gnutls/gnutls.h),-idirafter /usr/include)
ZLIB_LIB := $(shell zlib="$$( $(CC) -print-file-name=libz.a )"; \
	if [ "$$zlib" != "libz.a" ] && [ -f "$$zlib" ]; then \
		printf '%s' "$$zlib"; \
	elif [ -f ../Windows/zlib/x64/zlib1.lib ]; then \
		printf '%s' ../Windows/zlib/x64/zlib1.lib; \
	fi)

STRIP = strip

CPUFLAGS=
LDFLAGS = -m64 -mwindows -static-libgcc
LDFLAGS += $(QSS_LDFLAGS)
LDFLAGS += -Wl,--no-insert-timestamp	#prevent non-determinism in the exe header. mustn't be used for dlls.
DFLAGS ?=
CFLAGS ?= -m64 -Wall -Wno-trigraphs -MMD
CFLAGS += $(call check_gcc,-std=gnu11,)
CFLAGS += $(CPUFLAGS)
CFLAGS += $(QSS_CFLAGS)
ifneq ($(DEBUG),0)
DFLAGS += -DDEBUG
CFLAGS += -g
do_strip=
else
DFLAGS += -DNDEBUG
CFLAGS += -O2
#CFLAGS += -fno-asynchronous-unwind-tables
CFLAGS += $(call check_gcc,-fweb,)
CFLAGS += $(call check_gcc,-frename-registers,)
cmd_strip=$(STRIP) $(1)
define do_strip
	$(call cmd_strip,$(1));
endef
endif

ifeq ($(USE_SDL2),1)
CFLAGS += -DUSE_SDL2
endif

# default to our local SDL[2] for build
ifeq ($(USE_SDL2),1)
SDL_CONFIG ?=../Windows/SDL2/bin/sdl2-config --prefix=../Windows/SDL2 --lib-suffix=64
else
SDL_CONFIG ?=../Windows/SDL/bin/sdl-config --prefix=../Windows/SDL --lib-suffix=64
endif
SDL_CFLAGS := $(shell $(SDL_CONFIG) --cflags)
SDL_LIBS   := $(shell $(SDL_CONFIG) --libs)

DEFWINSOCK :=-D_USE_WINSOCK2
LIBWINSOCK := -lws2_32

CFLAGS     += $(DEFWINSOCK)
NET_LIBS   := $(LIBWINSOCK)

NET_LIBS   += -lcurl
CFLAGS     += -I../Windows/curl/include
LDFLAGS    += -L../Windows/curl/lib/x64

ifneq ($(VORBISLIB),vorbis)
ifneq ($(VORBISLIB),tremor)
$(error Invalid VORBISLIB setting)
endif
endif
ifneq ($(MP3LIB),mpg123)
ifneq ($(MP3LIB),mad)
$(error Invalid MP3LIB setting)
endif
endif
ifeq ($(MP3LIB),mad)
mp3_obj=snd_mp3.o snd_mp3tag.o
lib_mp3dec=-lmad
endif
ifeq ($(MP3LIB),mpg123)
mp3_obj=snd_mpg123.o snd_mp3tag.o
lib_mp3dec=-lmpg123
endif
ifeq ($(VORBISLIB),vorbis)
cpp_vorbisdec=
lib_vorbisdec=-lvorbisfile -lvorbis -logg
endif
ifeq ($(VORBISLIB),tremor)
cpp_vorbisdec=-DVORBIS_USE_TREMOR
lib_vorbisdec=-lvorbisidec -logg
endif

CODECLIBS  :=
ifeq ($(USE_CODEC_WAVE),1)
CFLAGS+= -DUSE_CODEC_WAVE
endif
ifeq ($(USE_CODEC_FLAC),1)
CFLAGS+= -DUSE_CODEC_FLAC
CODEC_INC = -I../Windows/codecs/include
CODEC_LINK= -L../Windows/codecs/x64
CODECLIBS+= -lFLAC
endif
ifeq ($(USE_CODEC_OPUS),1)
CFLAGS+= -DUSE_CODEC_OPUS
CODEC_INC = -I../Windows/codecs/include
CODEC_LINK= -L../Windows/codecs/x64
CODECLIBS+= -lopusfile -lopus -logg
endif
ifeq ($(USE_CODEC_VORBIS),1)
CFLAGS+= -DUSE_CODEC_VORBIS $(cpp_vorbisdec)
CODEC_INC = -I../Windows/codecs/include
CODEC_LINK= -L../Windows/codecs/x64
CODECLIBS+= $(lib_vorbisdec)
endif
ifeq ($(USE_CODEC_MP3),1)
CFLAGS+= -DUSE_CODEC_MP3
CODEC_INC = -I../Windows/codecs/include
CODEC_LINK= -L../Windows/codecs/x64
CODECLIBS+= $(lib_mp3dec)
endif
ifeq ($(USE_CODEC_MIKMOD),1)
CFLAGS+= -DUSE_CODEC_MIKMOD
CODEC_INC = -I../Windows/codecs/include
CODEC_LINK= -L../Windows/codecs/x64
CODECLIBS+= -lmikmod
endif
ifeq ($(USE_CODEC_XMP),1)
CFLAGS+= -DUSE_CODEC_XMP
CODEC_INC = -I../Windows/codecs/include
CODEC_LINK= -L../Windows/codecs/x64
CODECLIBS+= -lxmp
endif
ifeq ($(USE_CODEC_MODPLUG),1)
CFLAGS+= -DUSE_CODEC_MODPLUG
CODEC_INC = -I../Windows/codecs/include
CODEC_LINK= -L../Windows/codecs/x64
CODECLIBS+= -lmodplug
endif
ifeq ($(USE_CODEC_UMX),1)
CFLAGS+= -DUSE_CODEC_UMX
endif
CFLAGS+= $(CODEC_INC)

COMMON_LIBS:= -lopengl32 -lwinmm

ifeq ($(USE_ZLIB),1)
CFLAGS+= -DUSE_ZLIB
CFLAGS+= -I../Windows/zlib/include
COMMON_LIBS+= $(ZLIB_LIB)
endif

ifeq ($(USE_GNUTLS),1)
ifeq ($(FORCE_GNUTLS_DYNAMIC),1)
CFLAGS+= -DUSE_GNUTLS $(GNUTLS_HOST_CFLAGS) $(GNUTLS_HOST_INC_FALLBACK)
$(warning forcing USE_GNUTLS dynamic-loader mode without pkg-config link flags)
else ifeq ($(GNUTLS_PKG_OK),yes)
CFLAGS+= -DUSE_GNUTLS -DGNUTLS_STATIC -DGNUTLS_INTERNAL_BUILD $(GNUTLS_PKG_CFLAGS)
COMMON_LIBS+= $(GNUTLS_PKG_LIBS)
else
$(warning gnutls not found via $(PKG_CONFIG); building without USE_GNUTLS. Install mingw gnutls dev packages or set PKG_CONFIG/PKG_CONFIG_LIBDIR)
endif
endif

LIBS := $(COMMON_LIBS) $(NET_LIBS) $(CODEC_LINK) $(CODECLIBS)

ICEOBJS:= ice_gnutls.o  ice_main.o  ice_mdns.o ice_quake.o ice_sctp.o  ice_socket.o  ice_stream.o  ice_json.o  ice_md5.o  ice_sha1.o  ice_sha2.o


# ---------------------------
# objects
# ---------------------------

MUSIC_OBJS:= bgmusic.o \
	snd_codec.o \
	snd_flac.o \
	snd_wave.o \
	snd_vorbis.o \
	snd_opus.o \
	$(mp3_obj) \
	snd_mikmod.o \
	snd_modplug.o \
	snd_xmp.o \
	snd_umx.o
COMOBJ_SND := snd_voip.o snd_dma.o snd_mix.o snd_mem.o $(MUSIC_OBJS)
SYSOBJ_SND := snd_sdl.o
SYSOBJ_CDA := cd_sdl.o
SYSOBJ_INPUT := in_sdl.o
SYSOBJ_GL_VID:= gl_vidsdl.o
SYSOBJ_NET := net_win.o net_wins.o net_wipx.o
SYSOBJ_SYS := pl_win.o sys_sdl_win.o
SYSOBJ_MAIN:= main_sdl.o
SYSOBJ_RES := QuakeSpasm.res

GLOBJS = \
	gl_refrag.o \
	gl_rlight.o \
	gl_rmain.o \
	gl_fog.o \
	gl_rmisc.o \
	r_part.o \
	r_part_fte.o \
	r_world.o \
	gl_screen.o \
	gl_sky.o \
	gl_warp.o \
	$(SYSOBJ_GL_VID) \
	gl_draw.o \
	image.o \
	gl_texmgr.o \
	gl_mesh.o \
	r_sprite.o \
	r_alias.o \
	r_brush.o \
	gl_model.o

OBJS := strlcat.o \
	strlcpy.o \
	$(GLOBJS) \
	$(SYSOBJ_INPUT) \
	$(COMOBJ_SND) \
	$(SYSOBJ_SND) \
	$(SYSOBJ_CDA) \
	$(SYSOBJ_NET) \
	$(ICEOBJS) \
	net_dgrm.o \
	net_loop.o \
	net_main.o \
	chase.o \
	cl_demo.o \
	cl_input.o \
	cl_main.o \
	cl_parse.o \
	cl_tent.o \
	console.o \
	iplog.o \
	keys.o \
	location.o \
	menu.o \
	sbar.o \
	view.o \
	wad.o \
	cmd.o \
	common.o \
	json.o \
	mdfour.o \
	fs_zip.o \
	crc.o \
	cvar.o \
	cfgfile.o \
	host.o \
	host_cmd.o \
	mathlib.o \
	pr_cmds.o \
	pr_ext.o \
	pr_edict.o \
	pr_exec.o \
	pmove.o \
	pmovetst.o \
	sv_main.o \
	sv_move.o \
	sv_phys.o \
	sv_user.o \
	world.o \
	zone.o \
	$(SYSOBJ_SYS) $(SYSOBJ_MAIN)

# ---------------------------
# targets / rules
# ---------------------------

.PHONY:	clean debug release

DEFAULT_TARGET := quakespasm.exe
all: $(DEFAULT_TARGET)

%.o:	%.c
	$(CC) $(DFLAGS) -c $(CFLAGS) $(SDL_CFLAGS) -o $@ $<
%.o:	ice/%.c
	$(CC) $(DFLAGS) -c $(CFLAGS) $(SDL_CFLAGS) -o $@ $<
ice_json.o:	ice/json.c
	$(CC) $(DFLAGS) -c $(CFLAGS) $(SDL_CFLAGS) -o $@ $<
ice_md5.o:	ice/md5.c
	$(CC) $(DFLAGS) -c $(CFLAGS) $(SDL_CFLAGS) -o $@ $<
ice_sha1.o:	ice/sha1.c
	$(CC) $(DFLAGS) -c $(CFLAGS) $(SDL_CFLAGS) -o $@ $<
ice_sha2.o:	ice/sha2.c
	$(CC) $(DFLAGS) -c $(CFLAGS) $(SDL_CFLAGS) -o $@ $<
%.res:	../Windows/%.rc
	$(WINDRES) -I../Windows --output-format=coff --target=pe-x86-64 -o $@ $<

quakespasm.exe: $(OBJS) $(SYSOBJ_RES)
	$(LINKER) $(OBJS) $(SYSOBJ_RES) $(LDFLAGS) $(LIBS) $(SDL_LIBS) -o $@
	$(call do_strip,$@)

release:	quakespasm.exe
debug:
	$(error Use "make DEBUG=1")

clean:
	$(RM) *.o *.d *.res $(DEFAULT_TARGET)

sinclude $(OBJS:.o=.d)
